import 'package:color_iq_utils/color_iq_utils.dart';

enum MajorColorFamily {
  red('I. Red'),
  redOrange('II. Red-Orange'),
  orange('III. Orange'),
  yellowOrange('IV. Yellow-Orange'),
  yellow('V. Yellow'),
  yellowGreen('VI. Yellow-Green'),
  green('VII. Green'),
  blueGreen('VIII. Blue-Green'),
  blue('IX. Blue'),
  blueViolet('X. Blue-Violet'),
  violet('XI. Violet'),
  redViolet('XII. Red-Violet');

  const MajorColorFamily(this.displayName);
  final String displayName;
}

class ColorSegment {
  final MajorColorFamily majorFamily;
  final int segmentNo;
  final double hueStart;
  final double hueEnd;
  final double midpointH;
  final String name;
  final ColorIQ color;

  const ColorSegment({
    required this.majorFamily,
    required this.segmentNo,
    required this.hueStart,
    required this.hueEnd,
    required this.midpointH,
    required this.name,
    required this.color,
  });
}

// Helper to parse hex color string
ColorIQ _hexToColor(final String hexString) {
  final String hexCode = hexString.replaceAll('#', '');
  return ColorIQ(int.parse('FF$hexCode', radix: 16));
}

final List<ColorSegment> colorSegments = <ColorSegment>[
  ColorSegment(
    majorFamily: MajorColorFamily.red,
    segmentNo: 1,
    hueStart: 357,
    hueEnd: 3,
    midpointH: 0,
    name: 'Primary Red',
    color: _hexToColor('#E1413C'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.red,
    segmentNo: 2,
    hueStart: 3,
    hueEnd: 9,
    midpointH: 6,
    name: 'Warm Red',
    color: _hexToColor('#E73B35'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.red,
    segmentNo: 3,
    hueStart: 9,
    hueEnd: 15,
    midpointH: 12,
    name: 'Rich Red',
    color: _hexToColor('#EB3530'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.red,
    segmentNo: 4,
    hueStart: 15,
    hueEnd: 21,
    midpointH: 18,
    name: 'Ruby Red',
    color: _hexToColor('#EF2F2B'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.red,
    segmentNo: 5,
    hueStart: 21,
    hueEnd: 27,
    midpointH: 24,
    name: 'Scarlet Red',
    color: _hexToColor('#F22926'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redOrange,
    segmentNo: 6,
    hueStart: 27,
    hueEnd: 33,
    midpointH: 30,
    name: 'Sunset Red',
    color: _hexToColor('#F52422'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redOrange,
    segmentNo: 7,
    hueStart: 33,
    hueEnd: 39,
    midpointH: 36,
    name: 'Coral Red',
    color: _hexToColor('#F71E1D'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redOrange,
    segmentNo: 8,
    hueStart: 39,
    hueEnd: 45,
    midpointH: 42,
    name: 'Vermillion',
    color: _hexToColor('#F81A1A'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redOrange,
    segmentNo: 9,
    hueStart: 45,
    hueEnd: 51,
    midpointH: 48,
    name: 'Tangerine',
    color: _hexToColor('#F81517'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redOrange,
    segmentNo: 10,
    hueStart: 51,
    hueEnd: 57,
    midpointH: 54,
    name: 'Burnt Orange',
    color: _hexToColor('#F71216'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.orange,
    segmentNo: 11,
    hueStart: 57,
    hueEnd: 63,
    midpointH: 60,
    name: 'Citrus Orange',
    color: _hexToColor('#F51015'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.orange,
    segmentNo: 12,
    hueStart: 63,
    hueEnd: 69,
    midpointH: 66,
    name: 'Vibrant Orange',
    color: _hexToColor('#F30F15'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.orange,
    segmentNo: 13,
    hueStart: 69,
    hueEnd: 75,
    midpointH: 72,
    name: 'Carrot Orange',
    color: _hexToColor('#F01116'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.orange,
    segmentNo: 14,
    hueStart: 75,
    hueEnd: 81,
    midpointH: 78,
    name: 'Safety Orange',
    color: _hexToColor('#EC1518'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.orange,
    segmentNo: 15,
    hueStart: 81,
    hueEnd: 87,
    midpointH: 84,
    name: 'Gold Orange',
    color: _hexToColor('#E71D1D'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowOrange,
    segmentNo: 16,
    hueStart: 87,
    hueEnd: 93,
    midpointH: 90,
    name: 'Amber',
    color: _hexToColor('#E12826'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowOrange,
    segmentNo: 17,
    hueStart: 93,
    hueEnd: 99,
    midpointH: 96,
    name: 'Goldenrod',
    color: _hexToColor('#DB3531'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowOrange,
    segmentNo: 18,
    hueStart: 99,
    hueEnd: 105,
    midpointH: 102,
    name: 'Marigold',
    color: _hexToColor('#D3453D'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowOrange,
    segmentNo: 19,
    hueStart: 105,
    hueEnd: 111,
    midpointH: 108,
    name: 'Saffron',
    color: _hexToColor('#CA584F'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowOrange,
    segmentNo: 20,
    hueStart: 111,
    hueEnd: 117,
    midpointH: 114,
    name: 'Deep Yellow',
    color: _hexToColor('#BF6D63'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellow,
    segmentNo: 21,
    hueStart: 117,
    hueEnd: 123,
    midpointH: 120,
    name: 'Primary Yellow',
    color: _hexToColor('#B38279'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellow,
    segmentNo: 22,
    hueStart: 123,
    hueEnd: 129,
    midpointH: 126,
    name: 'Canary Yellow',
    color: _hexToColor('#A7968F'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellow,
    segmentNo: 23,
    hueStart: 129,
    hueEnd: 135,
    midpointH: 132,
    name: 'Lemon Yellow',
    color: _hexToColor('#9AA9A7'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellow,
    segmentNo: 24,
    hueStart: 135,
    hueEnd: 141,
    midpointH: 138,
    name: 'Neon Yellow',
    color: _hexToColor('#8BBBBF'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellow,
    segmentNo: 25,
    hueStart: 141,
    hueEnd: 147,
    midpointH: 144,
    name: 'Chartreuse Yellow',
    color: _hexToColor('#7BCACB'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowGreen,
    segmentNo: 26,
    hueStart: 147,
    hueEnd: 153,
    midpointH: 150,
    name: 'Acid Green',
    color: _hexToColor('#6CD9D7'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowGreen,
    segmentNo: 27,
    hueStart: 153,
    hueEnd: 159,
    midpointH: 156,
    name: 'Lime Green',
    color: _hexToColor('#5DD9D8'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowGreen,
    segmentNo: 28,
    hueStart: 159,
    hueEnd: 165,
    midpointH: 162,
    name: 'Pea Green',
    color: _hexToColor('#4ED8D8'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowGreen,
    segmentNo: 29,
    hueStart: 165,
    hueEnd: 171,
    midpointH: 168,
    name: 'Granny Smith',
    color: _hexToColor('#40D7D7'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.yellowGreen,
    segmentNo: 30,
    hueStart: 171,
    hueEnd: 177,
    midpointH: 174,
    name: 'Spring Bud',
    color: _hexToColor('#31D6D5'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.green,
    segmentNo: 31,
    hueStart: 177,
    hueEnd: 183,
    midpointH: 180,
    name: 'Primary Green',
    color: _hexToColor('#23D3D3'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.green,
    segmentNo: 32,
    hueStart: 183,
    hueEnd: 189,
    midpointH: 186,
    name: 'Emerald Green',
    color: _hexToColor('#20D1D2'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.green,
    segmentNo: 33,
    hueStart: 189,
    hueEnd: 195,
    midpointH: 192,
    name: 'Forest Green',
    color: _hexToColor('#1DCECF'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.green,
    segmentNo: 34,
    hueStart: 195,
    hueEnd: 201,
    midpointH: 198,
    name: 'Sea Green',
    color: _hexToColor('#1ACECC'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.green,
    segmentNo: 35,
    hueStart: 201,
    hueEnd: 207,
    midpointH: 204,
    name: 'Pine Green',
    color: _hexToColor('#18C8C7'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueGreen,
    segmentNo: 36,
    hueStart: 207,
    hueEnd: 213,
    midpointH: 210,
    name: 'Aqua',
    color: _hexToColor('#16C5C5'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueGreen,
    segmentNo: 37,
    hueStart: 213,
    hueEnd: 219,
    midpointH: 216,
    name: 'Teal',
    color: _hexToColor('#15C1C2'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueGreen,
    segmentNo: 38,
    hueStart: 219,
    hueEnd: 225,
    midpointH: 222,
    name: 'Cyan',
    color: _hexToColor('#13BFBF'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueGreen,
    segmentNo: 39,
    hueStart: 225,
    hueEnd: 231,
    midpointH: 228,
    name: 'Turquoise',
    color: _hexToColor('#11BCBD'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueGreen,
    segmentNo: 40,
    hueStart: 231,
    hueEnd: 237,
    midpointH: 234,
    name: 'Robin\'s Egg Blue',
    color: _hexToColor('#0FBBBC'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blue,
    segmentNo: 41,
    hueStart: 237,
    hueEnd: 243,
    midpointH: 240,
    name: 'Primary Blue',
    color: _hexToColor('#0EBAAA'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blue,
    segmentNo: 42,
    hueStart: 243,
    hueEnd: 249,
    midpointH: 246,
    name: 'Sky Blue',
    color: _hexToColor('#0DAAA0'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blue,
    segmentNo: 43,
    hueStart: 249,
    hueEnd: 255,
    midpointH: 252,
    name: 'Cerulean Blue',
    color: _hexToColor('#0B9A98'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blue,
    segmentNo: 44,
    hueStart: 255,
    hueEnd: 261,
    midpointH: 258,
    name: 'Royal Blue',
    color: _hexToColor('#0A8A91'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blue,
    segmentNo: 45,
    hueStart: 261,
    hueEnd: 267,
    midpointH: 264,
    name: 'Navy Blue',
    color: _hexToColor('#087A89'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueViolet,
    segmentNo: 46,
    hueStart: 267,
    hueEnd: 273,
    midpointH: 270,
    name: 'Indigo',
    color: _hexToColor('#056980'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueViolet,
    segmentNo: 47,
    hueStart: 273,
    hueEnd: 279,
    midpointH: 276,
    name: 'Midnight Blue',
    color: _hexToColor('#035976'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueViolet,
    segmentNo: 48,
    hueStart: 279,
    hueEnd: 285,
    midpointH: 282,
    name: 'Deep Cobalt',
    color: _hexToColor('#00486C'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueViolet,
    segmentNo: 49,
    hueStart: 285,
    hueEnd: 291,
    midpointH: 288,
    name: 'Periwinkle',
    color: _hexToColor('#003762'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.blueViolet,
    segmentNo: 50,
    hueStart: 291,
    hueEnd: 297,
    midpointH: 294,
    name: 'Amethyst',
    color: _hexToColor('#002758'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.violet,
    segmentNo: 51,
    hueStart: 297,
    hueEnd: 303,
    midpointH: 300,
    name: 'Primary Violet',
    color: _hexToColor('#00154E'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.violet,
    segmentNo: 52,
    hueStart: 303,
    hueEnd: 309,
    midpointH: 306,
    name: 'Lavender',
    color: _hexToColor('#0F0051'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.violet,
    segmentNo: 53,
    hueStart: 309,
    hueEnd: 315,
    midpointH: 312,
    name: 'Lilac',
    color: _hexToColor('#290054'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.violet,
    segmentNo: 54,
    hueStart: 315,
    hueEnd: 321,
    midpointH: 318,
    name: 'Plum',
    color: _hexToColor('#430058'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.violet,
    segmentNo: 55,
    hueStart: 321,
    hueEnd: 327,
    midpointH: 324,
    name: 'Iris',
    color: _hexToColor('#5C005B'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redViolet,
    segmentNo: 56,
    hueStart: 327,
    hueEnd: 333,
    midpointH: 330,
    name: 'Magenta',
    color: _hexToColor('#75005D'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redViolet,
    segmentNo: 57,
    hueStart: 333,
    hueEnd: 339,
    midpointH: 336,
    name: 'Fuchsia',
    color: _hexToColor('#8D005E'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redViolet,
    segmentNo: 58,
    hueStart: 339,
    hueEnd: 345,
    midpointH: 342,
    name: 'Rose',
    color: _hexToColor('#A4005E'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redViolet,
    segmentNo: 59,
    hueStart: 345,
    hueEnd: 351,
    midpointH: 348,
    name: 'Crimson',
    color: _hexToColor('#BC005E'),
  ),
  ColorSegment(
    majorFamily: MajorColorFamily.redViolet,
    segmentNo: 60,
    hueStart: 351,
    hueEnd: 357,
    midpointH: 354,
    name: 'Maroon',
    color: _hexToColor('#D2005E'),
  ),
];
