import 'package:color_iq_utils/src/constants.dart';

/// Color family categories for HTML colors
enum ColorFamily {
  red,
  orange,
  yellow,
  green,
  cyan,
  blue,
  purple,
  pink,
  brown,
  white,
  gray,
  black,
}

/// Standard HTML/CSS color names with their hex values
enum HTML {
  aliceBlue(0xFFF0F8FF, 'Alice Blue', ColorFamily.blue),
  antiqueWhite(0xFFFAEBD7, 'Antique White', ColorFamily.white),
  aqua(0xFF00FFFF, 'Aqua', ColorFamily.cyan),
  aquamarine(0xFF7FFFD4, 'Aquamarine', ColorFamily.cyan),
  azure(0xFFF0FFFF, 'Azure', ColorFamily.cyan),
  beige(0xFFF5F5DC, 'Beige', ColorFamily.white),
  bisque(0xFFFFE4C4, 'Bisque', ColorFamily.orange),
  black(0xFF000000, 'Black', ColorFamily.black),
  blanchedAlmond(0xFFFFEBCD, 'Blanched Almond', ColorFamily.white),
  blue(0xFF0000FF, 'Blue', ColorFamily.blue),
  blueViolet(0xFF8A2BE2, 'Blue Violet', ColorFamily.purple),
  brown(0xFFA52A2A, 'Brown', ColorFamily.brown),
  burlyWood(0xFFDEB887, 'BurlyWood', ColorFamily.brown),
  cadetBlue(0xFF5F9EA0, 'Cadet Blue', ColorFamily.blue),
  chartreuse(0xFF7FFF00, 'Chartreuse', ColorFamily.green),
  chocolate(0xFFD2691E, 'Chocolate', ColorFamily.brown),
  coral(0xFFFF7F50, 'Coral', ColorFamily.orange),
  cornflowerBlue(0xFF6495ED, 'CornflowerBlue', ColorFamily.blue),
  cornsilk(0xFFFFF8DC, 'Cornsilk', ColorFamily.white),
  crimson(0xFFDC143C, 'Crimson', ColorFamily.red),
  cyan(0xFF00FFFF, 'Cyan', ColorFamily.cyan),
  darkBlue(0xFF00008B, 'Dark Blue', ColorFamily.blue),
  darkCyan(0xFF008B8B, 'Dark Cyan', ColorFamily.cyan),
  darkGoldenRod(0xFFB8860B, 'DarkGoldenRod', ColorFamily.yellow),
  darkGray(0xFFA9A9A9, 'Dark Gray', ColorFamily.gray),
  darkGrey(0xFFA9A9A9, 'DarkGrey', ColorFamily.gray),
  darkGreen(0xFF006400, 'Dark Green', ColorFamily.green),
  darkKhaki(0xFFBDB76B, 'Dark Khaki', ColorFamily.yellow),
  darkMagenta(0xFF8B008B, 'Dark Magenta', ColorFamily.purple),
  darkOliveGreen(0xFF556B2F, 'Dark OliveGreen', ColorFamily.green),
  darkOrange(0xFFFF8C00, 'DarkOrange', ColorFamily.orange),
  darkOrchid(0xFF9932CC, 'DarkOrchid', ColorFamily.purple),
  darkRed(0xFF8B0000, 'DarkRed', ColorFamily.red),
  darkSalmon(0xFFE9967A, 'DarkSalmon', ColorFamily.orange),
  darkSeaGreen(0xFF8FBC8F, 'DarkSeaGreen', ColorFamily.green),
  darkSlateBlue(0xFF483D8B, 'DarkSlateBlue', ColorFamily.blue),
  darkSlateGray(0xFF2F4F4F, 'Dark SlateGray', ColorFamily.gray),
  darkSlateGrey(0xFF2F4F4F, 'Dark SlateGrey', ColorFamily.gray),
  darkTurquoise(0xFF00CED1, 'Dark Turquoise', ColorFamily.cyan),
  darkViolet(0xFF9400D3, 'Dark Violet', ColorFamily.purple),
  deepPink(0xFFFF1493, 'Deep Pink', ColorFamily.pink),
  deepSkyBlue(0xFF00BFFF, 'Deep SkyBlue', ColorFamily.blue),
  dimGray(0xFF696969, 'DimGray', ColorFamily.gray),
  dimGrey(0xFF696969, 'DimGrey', ColorFamily.gray),
  dodgerBlue(0xFF1E90FF, 'DodgerBlue', ColorFamily.blue),
  fireBrick(0xFFB22222, 'FireBrick', ColorFamily.red),
  floralWhite(0xFFFFFAF0, 'Floral White', ColorFamily.white),
  forestGreen(0xFF228B22, 'Forest Green', ColorFamily.green),
  fuchsia(0xFFFF00FF, 'Fuchsia', ColorFamily.purple),
  gainsboro(0xFFDCDCDC, 'Gainsboro', ColorFamily.gray),
  ghostWhite(0xFFF8F8FF, 'Ghost White', ColorFamily.white),
  gold(0xFFFFD700, 'Gold', ColorFamily.yellow),
  goldenRod(0xFFDAA520, 'GoldenRod', ColorFamily.yellow),
  gray(0xFF808080, 'Gray', ColorFamily.gray),
  grey(0xFF808080, 'Grey', ColorFamily.gray),
  green(0xFF008000, 'Green', ColorFamily.green),
  greenYellow(0xFFADFF2F, 'Green Yellow', ColorFamily.green),
  honeyDew(0xFFF0FFF0, 'HoneyDew', ColorFamily.white),
  hotPink(0xFFFF69B4, 'HotPink', ColorFamily.pink),
  indianRed(0xFFCD5C5C, 'IndianRed', ColorFamily.red),
  indigo(0xFF4B0082, 'Indigo', ColorFamily.purple),
  ivory(0xFFFFFFF0, 'Ivory', ColorFamily.white),
  khaki(0xFFF0E68C, 'Khaki', ColorFamily.yellow),
  lavender(0xFFE6E6FA, 'Lavender', ColorFamily.purple),
  lavenderBlush(0xFFFFF0F5, 'LavenderBlush', ColorFamily.pink),
  lawnGreen(0xFF7CFC00, 'Lawn Green', ColorFamily.green),
  lemonChiffon(0xFFFFFACD, 'Lemon Chiffon', ColorFamily.yellow),
  lightBlue(0xFFADD8E6, 'Light Blue', ColorFamily.blue),
  lightCoral(0xFFF08080, 'Light Coral', ColorFamily.orange),
  lightCyan(0xFFE0FFFF, 'Light Cyan', ColorFamily.cyan),
  lightGoldenRodYellow(
    0xFFFAFAD2,
    'Light GoldenRod Yellow',
    ColorFamily.yellow,
  ),
  lightGray(0xFFD3D3D3, 'Light Gray', ColorFamily.gray),
  lightGrey(0xFFD3D3D3, 'Light Grey', ColorFamily.gray),
  lightGreen(0xFF90EE90, 'Light Green', ColorFamily.green),
  lightPink(0xFFFFB6C1, 'LightPink', ColorFamily.pink),
  lightSalmon(0xFFFFA07A, 'Light Salmon', ColorFamily.orange),
  lightSeaGreen(0xFF20B2AA, 'Light SeaGreen', ColorFamily.green),
  lightSkyBlue(0xFF87CEFA, 'Light SkyBlue', ColorFamily.blue),
  lightSlateGray(0xFF778899, 'Light SlateGray', ColorFamily.gray),
  lightSlateGrey(0xFF778899, 'Light SlateGrey', ColorFamily.gray),
  lightSteelBlue(0xFFB0C4DE, 'Light SteelBlue', ColorFamily.blue),
  lightYellow(0xFFFFFFE0, 'Light Yellow', ColorFamily.yellow),
  lime(0xFF00FF00, 'Lime', ColorFamily.green),
  limeGreen(0xFF32CD32, 'Lime Green', ColorFamily.green),
  linen(0xFFFAF0E6, 'Linen', ColorFamily.white),
  magenta(0xFFFF00FF, kMagenta, ColorFamily.purple),
  maroon(0xFF800000, 'Maroon', ColorFamily.red),
  mediumAquaMarine(0xFF66CDAA, 'Medium AquaMarine', ColorFamily.cyan),
  mediumBlue(0xFF0000CD, 'Medium Blue', ColorFamily.blue),
  mediumOrchid(0xFFBA55D3, 'Medium Orchid', ColorFamily.purple),
  mediumPurple(0xFF9370DB, 'Medium Purple', ColorFamily.purple),
  mediumSeaGreen(0xFF3CB371, 'MediumSeaGreen', ColorFamily.green),
  mediumSlateBlue(0xFF7B68EE, 'MediumSlateBlue', ColorFamily.blue),
  mediumSpringGreen(0xFF00FA9A, 'Medium SpringGreen', ColorFamily.green),
  mediumTurquoise(0xFF48D1CC, 'MediumTurquoise', ColorFamily.cyan),
  mediumVioletRed(0xFFC71585, 'MediumVioletRed', ColorFamily.pink),
  midnightBlue(0xFF191970, 'MidnightBlue', ColorFamily.blue),
  mintCream(0xFFF5FFFA, 'Mint Cream', ColorFamily.white),
  mistyRose(0xFFFFE4E1, 'MistyRose', ColorFamily.pink),
  moccasin(0xFFFFE4B5, 'Moccasin', ColorFamily.orange),
  navajoWhite(0xFFFFDEAD, 'Navajo White', ColorFamily.orange),
  navy(0xFF000080, 'Navy', ColorFamily.blue),
  oldLace(0xFFFDF5E6, 'Old Lace', ColorFamily.white),
  olive(0xFF808000, 'Olive', ColorFamily.green),
  oliveDrab(0xFF6B8E23, 'Olive Drab', ColorFamily.green),
  orange(0xFFFFA500, 'Orange', ColorFamily.orange),
  orangeRed(0xFFFF4500, 'OrangeRed', ColorFamily.orange),
  orchid(0xFFDA70D6, 'Orchid', ColorFamily.purple),
  paleGoldenRod(0xFFEEE8AA, 'Pale GoldenRod', ColorFamily.yellow),
  paleGreen(0xFF98FB98, 'Pale Green', ColorFamily.green),
  paleTurquoise(0xFFAFEEEE, 'Pale Turquoise', ColorFamily.cyan),
  paleVioletRed(0xFFDB7093, 'PaleVioletRed', ColorFamily.pink),
  papayaWhip(0xFFFFEFD5, 'PapayaWhip', ColorFamily.orange),
  peachPuff(0xFFFFDAB9, 'PeachPuff', ColorFamily.orange),
  peru(0xFFCD853F, 'Peru', ColorFamily.orange),
  pink(0xFFFFC0CB, 'Pink', ColorFamily.pink),
  plum(0xFFDDA0DD, 'Plum', ColorFamily.purple),
  powderBlue(0xFFB0E0E6, 'Powder Blue', ColorFamily.blue),
  purple(0xFF800080, 'Purple', ColorFamily.purple),
  rebeccaPurple(0xFF663399, 'Rebecca Purple', ColorFamily.purple),
  red(0xFFFF0000, 'Red', ColorFamily.red),
  rosyBrown(0xFFBC8F8F, 'Rosy Brown', ColorFamily.brown),
  royalBlue(0xFF4169E1, 'Royal Blue', ColorFamily.blue),
  saddleBrown(0xFF8B4513, 'Saddle Brown', ColorFamily.brown),
  salmon(0xFFFA8072, 'Salmon', ColorFamily.orange),
  sandyBrown(0xFFF4A460, 'Sandy Brown', ColorFamily.orange),
  seaGreen(0xFF2E8B57, 'SeaGreen', ColorFamily.green),
  seaShell(0xFFFFF5EE, 'SeaShell', ColorFamily.white),
  sienna(0xFFA0522D, 'Sienna', ColorFamily.brown),
  silver(0xFFC0C0C0, 'Silver', ColorFamily.gray),
  skyBlue(0xFF87CEEB, 'SkyBlue', ColorFamily.blue),
  slateBlue(0xFF6A5ACD, 'Slate Blue', ColorFamily.blue),
  slateGray(0xFF708090, 'Slate Gray', ColorFamily.gray),
  slateGrey(0xFF708090, 'SlateGrey', ColorFamily.gray),
  snow(0xFFFFFAFA, 'Snow', ColorFamily.white),
  springGreen(0xFF00FF7F, 'SpringGreen', ColorFamily.green),
  steelBlue(0xFF4682B4, 'Steel Blue', ColorFamily.blue),
  tan(0xFFD2B48C, 'Tan', ColorFamily.brown),
  teal(0xFF008080, 'Teal', ColorFamily.cyan),
  thistle(0xFFD8BFD8, 'Thistle', ColorFamily.purple),
  tomato(0xFFFF6347, 'Tomato', ColorFamily.red),
  turquoise(0xFF40E0D0, 'Turquoise', ColorFamily.cyan),
  violet(0xFFEE82EE, 'Violet', ColorFamily.purple),
  wheat(0xFFF5DEB3, 'Wheat', ColorFamily.brown),
  white(0xFFFFFFFF, 'White', ColorFamily.white),
  whiteSmoke(0xFFF5F5F5, 'White Smoke', ColorFamily.white),
  yellow(0xFFFFFF00, 'Yellow', ColorFamily.yellow),
  yellowGreen(0xFF9ACD32, 'Yellow Green', ColorFamily.green);

  final int value;
  final String name;
  final ColorFamily family;
  const HTML(this.value, this.name, this.family);
  int get hexId => value;
  String get hexString =>
      '0x${value.toRadixString(16).toUpperCase().padLeft(8, '0')})';
}
